### ISSUE TITLE
RSSelection menu Action Sheet

### ISSUE THREAD

**Issue by saitejapanditi67** [rushisangani/RSSelectionMenu#89] opened 2019-10-25 18:24 UTC
Unable to set the done or cancel button in the action sheet

**Comment by AmjadAlSawafta** [comment] 2019-11-16 17:29
I opened a pull request to resolve this issue https://github.com/rushisangani/RSSelectionMenu/pull/91

**Comment by AmjadAlSawafta** [comment] 2019-11-16 17:45
You can use my fork as a temp solution until the pull request is being merged.

>   pod 'RSSelectionMenu', :git => 'https://github.com/AmjadAlSawafta/RSSelectionMenu.git', :tag => '6.0.7'

**Comment by saitejapanditi67** [comment] 2019-11-18 06:09
> I opened a pull request to resolve this issue #91

Thank you for your reply. the code in #91 is working only for the below versions of iOS 13. it's not working on iOS 13.

**Comment by AmjadAlSawafta** [comment] 2019-11-26 01:47
@saitejapanditi67 Welcome.
I opened another revision and tagged it '6.0.8'. I hope it will work probably on the  iOS 13.

**Comment by dilipbhuva** [comment] 2019-12-06 08:43
You can not set UIAlertAction style to cancel for iPad,  popover will not display that type of action.
Change  in RSSelectionMenuController.swift -> getAlertViewController 
let doneAction = UIAlertAction(title: actionTitle, style: .default) { [weak self] (doneButton) in
            self?.menuWillDismiss()
 }
style: should be  .default to show Done Button in ActionSheet.

**Comment by mehulparmar4ever** [comment] 2020-01-10 13:32
Hello @all,

The issue is still existed but only for iPad below iOS 13.

The code is working fine in iOS 13 but not in iOS 12.
See, "Done" button is not visible in iOS 12.

See this: <img width="1063" alt="Screenshot 2020-01-10 at 7 00 44 PM" src="https://user-images.githubusercontent.com/7687920/72156434-89255100-33db-11ea-8e6c-8631996940b2.png">


Does anyone have a solution?

Help needed
#91

**Closed** 2020-02-16 14:00 UTC
Labels: wontfix
